export enum CodeProejects {
  BUBBLE_CHART = "BUBBLE_CHART",
  GAME_OF_LIFE = "GAME_OF_LIFE",
  CHAT_AI = "CHAT_AI",
  RECIPES = "RECIPES",
  WATCHES = "WATCHES",
  WORD_CLOCK = "WORD_CLOCK",
  THREE_JS = "THREE_JS",
  TEST = "TEST",
}
